# Generated by Django 4.2.29 on 2026-03-16 21:06

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('SUPERUSER', 'Superuser'), ('ADMIN', 'Administrator'), ('UNDERWRITER', 'Underwriter'), ('CLAIMS_OFFICER', 'Claims Officer'), ('FINANCE_OFFICER', 'Finance Officer'), ('AGENT', 'Sales Agent'), ('READ_ONLY', 'Read-Only Viewer')], default='READ_ONLY', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'System User',
                'verbose_name_plural': 'System Users',
                'db_table': 'auth_user',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChurnBatchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('total_customers', models.PositiveIntegerField(default=0)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'churn_batch_jobs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChurnPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('churn_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_churned', models.BooleanField(default=False, help_text='Set True when customer actually churns — used for model retraining')),
                ('model_version', models.CharField(max_length=50)),
                ('predicted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='churn.churnbatchjob')),
            ],
            options={
                'db_table': 'churn_predictions',
                'ordering': ['-predicted_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('claim_type', models.CharField(choices=[('DEATH', 'Death Benefit'), ('DISABILITY', 'Disability'), ('MEDICAL', 'Medical'), ('MATURITY', 'Maturity'), ('SURRENDER', 'Surrender'), ('REPATRIATION', 'Repatriation')], max_length=20)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SETTLED', 'Settled'), ('WITHDRAWN', 'Withdrawn')], default='SUBMITTED', max_length=20)),
                ('event_date', models.DateField(help_text='Date the insured event occurred')),
                ('reported_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('amount_claimed', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_settled', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claims',
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_number', models.CharField(editable=False, help_text='Auto-generated human-readable reference e.g. NYC-000123', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('national_id', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{6,7}[A-Z]\\d{2}$', 'Enter a valid Zimbabwean National ID e.g. 63-123456A75')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_primary', models.CharField(max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ref_genders',
            },
        ),
        migrations.CreateModel(
            name='IncomeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('min_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'ref_income_levels',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('category', models.CharField(choices=[('PREMIUM', 'Premium'), ('CLAIM_PAYOUT', 'Claim Payout'), ('REFUND', 'Refund'), ('PENALTY', 'Late Payment Penalty')], default='PREMIUM', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('external_ref', models.CharField(blank=True, help_text='EcoCash / bank transaction reference', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(blank=True, help_text='Populated only for claim payout transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='churn.claim')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ref_payment_methods',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('sum_assured', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('premium_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMI_ANNUAL', 'Semi-Annual'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=20)),
                ('dependents', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('LAPSED', 'Lapsed'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated'), ('MATURED', 'Matured')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='churn.customer')),
            ],
            options={
                'db_table': 'policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ref_policy_types',
            },
        ),
        migrations.CreateModel(
            name='RiskLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('min_threshold', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_threshold', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color_hex', models.CharField(default='#000000', help_text='Hex colour for UI badges e.g. #FF0000', max_length=7)),
            ],
            options={
                'db_table': 'ref_risk_levels',
                'ordering': ['min_threshold'],
            },
        ),
        migrations.CreateModel(
            name='CustomerEngagement',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='engagement', serialize=False, to='churn.customer')),
                ('number_of_complaints', models.PositiveIntegerField(default=0)),
                ('claims_filed', models.PositiveIntegerField(default=0)),
                ('service_satisfaction', models.DecimalField(blank=True, decimal_places=1, help_text='CSAT score 0–10', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_engagement',
            },
        ),
        migrations.CreateModel(
            name='PremiumSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_late', models.BooleanField(default=False)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_schedule', to='churn.policy')),
            ],
            options={
                'db_table': 'premium_schedules',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('PROPOSAL', 'Proposal Form'), ('MEDICAL_REPORT', 'Medical Report'), ('ID_COPY', 'ID / Passport Copy'), ('ENDORSEMENT', 'Endorsement'), ('OTHER', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='policy_docs/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='churn.policy')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'policy_documents',
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='policy_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='churn.policytype'),
        ),
        migrations.AddField(
            model_name='policy',
            name='underwritten_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='underwritten_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='churn.payment')),
                ('premium_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='churn.premiumschedule')),
            ],
            options={
                'db_table': 'payment_allocations',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='churn.paymentmethod'),
        ),
        migrations.AddField(
            model_name='payment',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='churn.policy'),
        ),
        migrations.AddField(
            model_name='payment',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ref_locations',
                'unique_together': {('province', 'district', 'city')},
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='churn.gender'),
        ),
        migrations.AddField(
            model_name='customer',
            name='income_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='churn.incomelevel'),
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='churn.location'),
        ),
        migrations.AddField(
            model_name='customer',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClaimNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='churn.claim')),
            ],
            options={
                'db_table': 'claim_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('DEATH_CERT', 'Death Certificate'), ('POLICE_REPORT', 'Police Report'), ('MEDICAL_CERT', 'Medical Certificate'), ('AFFIDAVIT', 'Affidavit'), ('INVOICE', 'Invoice / Receipt'), ('OTHER', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='claim_docs/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='churn.claim')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claim_documents',
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='churn.policy'),
        ),
        migrations.CreateModel(
            name='ChurnPredictionFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_name', models.CharField(max_length=100)),
                ('feature_value', models.CharField(max_length=255)),
                ('feature_type', models.CharField(choices=[('NUMERIC', 'Numeric'), ('CATEGORICAL', 'Categorical'), ('BOOLEAN', 'Boolean')], max_length=20)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='churn.churnprediction')),
            ],
            options={
                'db_table': 'churn_prediction_features',
            },
        ),
        migrations.AddField(
            model_name='churnprediction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churn_predictions', to='churn.customer'),
        ),
        migrations.AddField(
            model_name='churnprediction',
            name='risk_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predictions', to='churn.risklevel'),
        ),
        migrations.AddIndex(
            model_name='premiumschedule',
            index=models.Index(fields=['policy', 'is_paid', 'due_date'], name='premium_sch_policy__470da3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='premiumschedule',
            unique_together={('policy', 'due_date')},
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['customer', 'status'], name='policies_custome_612bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['policy_number'], name='policies_policy__ca1bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['start_date', 'end_date'], name='policies_start_d_34ca2f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentallocation',
            unique_together={('payment', 'premium_schedule')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['policy', 'status'], name='payments_policy__e1157d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_date'], name='payments_transac_77d3e0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_reference'], name='payments_payment_2311ee_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'first_name'], name='customers_last_na_89bb5f_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['national_id'], name='customers_nationa_0499ab_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_number'], name='customers_custome_41ed98_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['policy', 'status'], name='claims_policy__a9ba66_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['claim_number'], name='claims_claim_n_b9e177_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['event_date'], name='claims_event_d_38e530_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='churnpredictionfeature',
            unique_together={('prediction', 'feature_name')},
        ),
        migrations.AddIndex(
            model_name='churnprediction',
            index=models.Index(fields=['customer', 'predicted_at'], name='churn_predi_custome_edfbe0_idx'),
        ),
        migrations.AddIndex(
            model_name='churnprediction',
            index=models.Index(fields=['risk_level'], name='churn_predi_risk_le_49b33b_idx'),
        ),
        migrations.AddIndex(
            model_name='churnprediction',
            index=models.Index(fields=['is_churned'], name='churn_predi_is_chur_012957_idx'),
        ),
    ]
