# Generated by Django 4.2.29 on 2026-03-30 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churn', '0003_loginattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginattempt',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='audit_login_email_b43a9b_idx',
            old_name='audit_logi_email_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='audit_login_ip_addr_907086_idx',
            old_name='audit_logi_ip_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='audit_login_success_267d5b_idx',
            old_name='audit_logi_success_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='audit_login_timesta_7d429a_idx',
            old_name='audit_logi_timestamp_idx',
        ),
    ]
