# Generated by Django 4.2.29 on 2026-04-01 17:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('churn', '0004_alter_loginattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ['label']},
        ),
        migrations.AlterModelOptions(
            name='incomelevel',
            options={'ordering': ['label']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['province', 'district', 'city']},
        ),
        migrations.AlterModelOptions(
            name='policytype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(editable=False, help_text='Auto-generated human-readable reference e.g. NYC-000123', max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PolicyBeneficiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('share_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='churn.policy')),
            ],
            options={
                'db_table': 'policy_beneficiaries',
                'ordering': ['-is_primary', 'full_name'],
            },
        ),
    ]
