# Generated by Django 4.2.29 on 2026-04-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("churn", "0005_alter_gender_options_alter_incomelevel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="account_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="claim",
            name="bank_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="claim",
            name="branch_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="claim",
            name="burial_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="claim",
            name="burial_place",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="claim",
            name="cause_of_death",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="claim",
            name="claimant_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="claim",
            name="claimant_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="claim",
            name="claimant_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="claim",
            name="claimant_relation",
            field=models.CharField(
                blank=True,
                help_text="Relationship to deceased (e.g., Spouse, Child)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="date_of_death",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="claim",
            name="deceased_name",
            field=models.CharField(
                blank=True, help_text="Full name of deceased", max_length=150, null=True
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="place_of_death",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
